export const sample_foods = [
    {
        id : '1',
        name: 'Veg Fried Rice',
        cookTime: '10-20',
        price: 10,
        favorite: false,
        stars: 4.5,
        imageUrl:'food.jpg',
        tags: ['Fastfood', 'Pizza', 'Lunch'],
    },
    {
        id : '2',
        name: 'Chicken Fried Rice',
        cookTime: '10-20',
        price: 10,
        favorite: false,
        stars: 4.5,
        imageUrl:'food.jpg',
        tags: ['Fastfood', 'Pizza', 'Lunch'],
    },
    {
        id : '3',
        name: 'Meatball',
        cookTime: '10-20',
        price: 10,
        favorite: false,
        stars: 4.5,
        imageUrl:'food.jpg',
        tags: ['Fastfood', 'Pizza', 'Lunch'],
    },
    {
        id : '4',
        name: 'Pizza',
        cookTime: '10-20',
        price: 10,
        favorite: false,
        stars: 4.5,
        imageUrl:'food.jpg',
        tags: ['Fastfood', 'Pizza', 'Lunch'],
    },
    {
        id : '5',
        name: 'Ice-Cream',
        cookTime: '10-20',
        price: 10,
        favorite: false,
        stars: 4.5,
        imageUrl:'food.jpg',
        tags: ['Fastfood', 'Pizza', 'Lunch'],
    },
    {
        id : '6',
        name: 'coffee',
        cookTime: '10-20',
        price: 10,
        favorite: false,
        stars: 4.5,
        imageUrl:'food.jpg',
        tags: ['Fastfood', 'Pizza', 'Lunch'],
    },
]

export const sample_users = [
    {
        id: 1,
        name: 'Amar Kumar',
        email: 'amar@gmail.com',
        password: '123456',
        address: 'Bihar In',
        isAdmin: false,
    },
    {
        id: 2,
        name: 'Aman Raj',
        email: 'raj@gmail.com',
        password: '1234567',
        address: 'Nashik In',
        isAdmin: true,
    },
]